# Generated by packaging/release-cli.sh. Do not hand-edit: the checksums must
# match the tarballs actually uploaded to Nexus, and a formula whose checksum is
# wrong fails at brew install for every user at once.
#
# The tap is cdm/tools, so the installed name is cdm/tools/cdm-share. The short
# name cdm/cdm-tools does NOT resolve. Committing this formula to
# github.com/cdm-ch/homebrew-cdm-tools is a separate owner action, and that tap
# takes direct commits on master rather than pull requests. See README.
class CdmShare < Formula
  desc "Publish a folder to the CDM artifact sharing service and print its URL"
  homepage "https://git.cdm.smis.ch/bitbucket/projects/CCPT/repos/share"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.cdm.smis.ch/repository/homebrew-binaries/cdm-share/1.0.3/cdm-share-1.0.3-darwin-intel.tar.gz"
      sha256 "5079b434202aa91d9a31737a4f123df1b1c712bb57a41dcfe6037af4d662ad97"
    else
      url "https://nexus.cdm.smis.ch/repository/homebrew-binaries/cdm-share/1.0.3/cdm-share-1.0.3-darwin-arm.tar.gz"
      sha256 "745f3694f2671ff415027a575cfbb45e5b973efc3bc3b96c3252b96625e2251d"
    end
  end

  def install
    bin.install "cdm-share"
  end

  test do
    system "#{bin}/cdm-share", "--version"
  end
end
