# Generated by packaging/release-cli.sh. Do not hand-edit: the checksums must
# match the tarballs actually uploaded to Nexus, and a formula whose checksum is
# wrong fails at brew install for every user at once.
#
# The tap is cdm/tools, so the installed name is cdm/tools/cdm-share. The short
# name cdm/cdm-tools does NOT resolve. Committing this formula to
# github.com/cdm-ch/homebrew-cdm-tools is a separate owner action, and that tap
# takes direct commits on master rather than pull requests. See README.
class CdmShare < Formula
  desc "Publish a folder to the CDM artifact sharing service and print its URL"
  homepage "https://git.cdm.smis.ch/bitbucket/projects/CCPT/repos/share"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.cdm.smis.ch/repository/homebrew-binaries/cdm-share/1.0.2/cdm-share-1.0.2-darwin-intel.tar.gz"
      sha256 "09d6d25e98938c7e8546a82cdb01cbc94c0a618d7541bdac37d3628671aa292f"
    else
      url "https://nexus.cdm.smis.ch/repository/homebrew-binaries/cdm-share/1.0.2/cdm-share-1.0.2-darwin-arm.tar.gz"
      sha256 "8801c5cc6db0d92a10f7f513efa6f95bb952f34f7cfc6bf19da65248d6f8360e"
    end
  end

  def install
    bin.install "cdm-share"
  end

  test do
    system "#{bin}/cdm-share", "--version"
  end
end
