# Generated by packaging/release-cli.sh. Do not hand-edit: the checksums must
# match the tarballs actually uploaded to Nexus, and a formula whose checksum is
# wrong fails at brew install for every user at once.
#
# The tap is cdm/tools, so the installed name is cdm/tools/cdm-share. The short
# name cdm/cdm-tools does NOT resolve. Opening the tap pull request against
# github.com/cdm-ch/homebrew-cdm-tools is a separate owner action.
class CdmShare < Formula
  desc "Publish a folder to the CDM artifact sharing service and print its URL"
  homepage "https://git.cdm.smis.ch/bitbucket/projects/CCPT/repos/share"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nexus.cdm.smis.ch/repository/homebrew-binaries/cdm-share/1.0.1/cdm-share-1.0.1-darwin-intel.tar.gz"
      sha256 "3297b54ef7f80f779efd69f642d760c330b67ea96af7989188cb66cd5ea6fdf6"
    else
      url "https://nexus.cdm.smis.ch/repository/homebrew-binaries/cdm-share/1.0.1/cdm-share-1.0.1-darwin-arm.tar.gz"
      sha256 "e168abd1f0310cd232bb3a7461363520060e36a2198f6063f3d222caef516e15"
    end
  end

  def install
    bin.install "cdm-share"
  end

  test do
    system "#{bin}/cdm-share", "--version"
  end
end
